### ISSUE TITLE
Test results and trained model for demo

### ISSUE THREAD

**Issue by SeaOfOcean** [andreaskoepf/faster-rcnn#10]
Hi, can you provide your test results, and saved final model for demo purpose? thanks!

**Comment by Yuliang-Zou** [comment]
Hi, I also want to test the framework on your trained model. I tried to train the vgg_small model on voc2007 model, but the performance is bad. Can you provide the corresponding model trained on Imagenet along with some test results?

**Comment by ClaraBing** [comment]
Hi, I wonder what kind of training strategy is used in this implementation. For example, is it using alternating training or joint training (as mentioned in the Faster RCNN paper)?

Besides, I would really appreciate it if someone could post the performance he/she obtained on ImageNet.

Thanks a lot!
